story_generation_task:
  description: >
    Create stories in JSON format for three specified proficiency levels: beginner, intermediate, and advanced. 
    Each story should have a title and narrative content appropriate for the target audience.
  expected_output: >
    A JSON object containing three keys: "beginner," "intermediate," and "advanced." 
    Each key should map to an object with a "title" and "story" field, where the "title" is a string and the "story" is also a string representing the narrative content.
  agent: story_creator

translation_and_keyword_extraction_task:
  description: >
    Translate the stories into Korean while extracting key vocabulary, providing results in JSON format. 
    Each proficiency level's output should include the translated title, story content with translations, and key vocabulary.
  expected_output: >
    A JSON object structured with three keys: "beginner," "intermediate," and "advanced." 
    For each key, the value should be an object containing a "title" field, which itself is an object with "en" and "ko" keys for the English and Korean titles respectively. 
    Additionally, there should be a "story" field that is an array of objects. 
    Each object in this array should contain an "en" field for the English sentence, a "ko" field for the Korean translation, and a "keywords" field, which is an array of objects containing "en" and "ko" keys for key vocabulary words in both languages.
    result must be in JSON format, not markdown.
  agent: translator